# Data Overview

Trying to undersand the dataset

In [1]:
import pandas as pd
import numpy as np

### Loading the dataset

In [2]:
df = pd.read_csv("raw_dataset.csv")

df.head(10)

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
0,Prefer Not to Say,Gay,Urban,High,Bachelor’s,"Fitness, Politics, Traveling",52,Moderate,0.60,Optimistic,173,23,4,44,75,0.36,13,Early Morning,Mutual Match
1,Male,Bisexual,Suburban,Upper-Middle,No Formal Education,"Languages, Fashion, Parenting",279,Extreme User,0.56,Optimistic,107,7,3,301,35,0.42,0,Morning,Chat Ignored
2,Non-binary,Pansexual,Suburban,Low,Master’s,"Movies, Reading, DIY",49,Moderate,0.41,Optimistic,91,27,2,309,33,0.41,1,After Midnight,Date Happened
3,Genderfluid,Gay,Metro,Very Low,Postdoc,"Coding, Podcasts, History",185,Extreme User,0.32,Balanced,147,6,5,35,5,0.07,21,Morning,No Action
4,Male,Bisexual,Urban,Middle,Bachelor’s,"Clubbing, Podcasts, Cars",83,High,0.32,Balanced,94,11,1,343,34,0.11,22,After Midnight,One-sided Like
5,Genderfluid,Lesbian,Small Town,High,Associate’s,"Anime, Clubbing, DIY",138,Addicted,0.62,Optimistic,163,22,4,112,87,0.18,10,Early Morning,Blocked
6,Male,Asexual,Metro,Lower-Middle,High School,"Tech, Makeup, Parenting",161,Addicted,0.38,Balanced,54,20,3,202,82,0.32,14,Morning,No Action
7,Female,Bisexual,Remote Area,Upper-Middle,Postdoc,"Spirituality, Sneaker Culture, Meditation",219,Extreme User,0.47,Optimistic,149,12,2,112,17,0.54,16,Evening,One-sided Like
8,Male,Gay,Suburban,High,Diploma,"MMA, Board Games, Startups",32,Moderate,0.23,Balanced,98,12,4,239,67,0.27,8,Late Night,Mutual Match
9,Prefer Not to Say,Gay,Remote Area,Upper-Middle,Bachelor’s,"Social Activism, Astrology, Photography",150,Addicted,0.68,Optimistic,111,5,3,1,92,0.27,23,Afternoon,Relationship Formed

### Displaying all the features

In [3]:
df.info()
df.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gender                50000 non-null  str
 1   sexual_orientation    50000 non-null  str
 2   location_type         50000 non-null  str
 3   income_bracket        50000 non-null  str
 4   education_level       50000 non-null  str
 5   interest_tags         50000 non-null  str
 6   app_usage_time_min    50000 non-null  int64
 7   app_usage_time_label  50000 non-null  str
 8   swipe_right_ratio     50000 non-null  float64
 9   swipe_right_label     50000 non-null  str
 10  likes_received        50000 non-null  int64
 11  mutual_matches        50000 non-null  int64
 12  profile_pics_count    50000 non-null  int64
 13  bio_length            50000 non-null  int64
 14  message_sent_count    50000 non-null  int64
 15  emoji_usage_rate      50000 non-null  float64
 16  last_active_hour      50000 non-null  int64
 17  swipe_time_of_day     50000 non-null  str
 18  match_outcome         50000 non-null  str
dtypes: float64(2), int64(7), str(10)
memory usage: 7.2 MB

,gender,sexual_orientation,location_type,income_bracket,education_level,interest_tags,app_usage_time_min,app_usage_time_label,swipe_right_ratio,swipe_right_label,likes_received,mutual_matches,profile_pics_count,bio_length,message_sent_count,emoji_usage_rate,last_active_hour,swipe_time_of_day,match_outcome
count,50000,50000,50000,50000,50000,50000,50000.000000,50000,50000.000000,50000,50000.000000,50000.000000,50000.00000,50000.000000,50000.00000,50000.000000,50000.000000,50000,50000
unique,6,8,6,7,9,40206,NaN,7,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,10
top,Female,Straight,Remote Area,High,Bachelor’s,"Fitness, Anime, Yoga",NaN,Extreme User,NaN,Optimistic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,After Midnight,One-sided Like
freq,8384,6326,8519,7309,5646,6,NaN,20140,NaN,26873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8524,5112
mean,NaN,NaN,NaN,NaN,NaN,NaN,149.912400,NaN,0.500655,NaN,99.526040,13.870280,2.98772,250.174400,50.07194,0.286205,11.521800,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,86.990521,NaN,0.197468,NaN,57.996799,9.105615,1.99678,144.800996,29.16800,0.160042,6.920474,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,74.000000,NaN,0.370000,NaN,49.000000,6.000000,1.00000,125.000000,25.00000,0.160000,5.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,NaN,0.500000,NaN,100.000000,13.000000,3.00000,250.000000,50.00000,0.270000,12.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,225.000000,NaN,0.640000,NaN,150.000000,22.000000,5.00000,376.000000,75.00000,0.390000,18.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,300.000000,NaN,1.000000,NaN,200.000000,30.000000,6.00000,500.000000,100.00000,0.940000,23.000000,NaN,NaN

### Displaying the Tags of Interest

In [4]:
tags_split = df['interest_tags'].dropna().astype(str).str.split(', ')

tags = tags_split.explode().str.strip().value_counts()

print("--- Most Popular Interest Tags ---")
print(tags)

--- Most Popular Interest Tags ---
interest_tags
Coding             3147
Gaming             3145
Motorcycling       3140
Binge-Watching     3131
Music              3109
Yoga               3108
Investing          3108
Reading            3106
Photography        3106
Art                3106
Traveling          3100
Clubbing           3097
Skating            3096
Makeup             3091
Dancing            3087
Spirituality       3085
Social Activism    3085
Cooking            3079
Board Games        3076
Crafting           3075
Cars               3070
Hiking             3070
Pets               3070
Podcasts           3069
Sneaker Culture    3066
Politics           3065
Startups           3065
Languages          3060
History            3060
Movies             3058
Parenting          3056
Painting           3053
Writing            3050
MMA                3049
Tattoos            3048
Memes              3046
Fashion            3042
Foodie             3033
K-pop              3022
Gardening          3008
Astrology          3001
Anime              2998
Tech               2995
Poetry             2990
Running            2988
Stand-up Comedy    2987
Meditation         2985
Fitness            2970
DIY                2949
Name: count, dtype: int64

In [5]:
tags_split = df['interest_tags'].dropna().astype(str).str.split(', ')
tags = tags_split.explode().str.strip().value_counts().reset_index()
tags.columns = ['interest_tags', 'interest_tags_count']

other_columns = [
    'gender', 'sexual_orientation', 'location_type', 'income_bracket', 
    'education_level', 'app_usage_time_label', 'swipe_right_label', 
    'swipe_time_of_day', 'match_outcome'
]

dfs_to_concat = [tags]

for col in other_columns:

    if col in df.columns:
    
        counts = df[col].value_counts().reset_index()
        counts.columns = [col, f'{col}_count']
        dfs_to_concat.append(counts)

summary_table = pd.concat(dfs_to_concat, axis=1)

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

print("--- Demographics & Usage Summary Table ---")
print(summary_table)

--- Demographics & Usage Summary Table ---
      interest_tags  interest_tags_count             gender  gender_count sexual_orientation  sexual_orientation_count location_type  location_type_count income_bracket  income_bracket_count      education_level  education_level_count app_usage_time_label  app_usage_time_label_count swipe_right_label  swipe_right_label_count swipe_time_of_day  swipe_time_of_day_count        match_outcome  match_outcome_count
0            Coding                 3147             Female        8384.0           Straight                    6326.0   Remote Area               8519.0           High                7309.0           Bachelor’s                 5646.0         Extreme User                     20140.0        Optimistic                  26873.0    After Midnight                   8524.0       One-sided Like               5112.0
1            Gaming                 3145         Non-binary        8366.0            Lesbian                    6315.0    Small Town               8343.0      Very High                7178.0                  MBA                 5637.0                 High                      9911.0          Balanced                  11730.0         Afternoon                   8344.0        Instant Match               5078.0
2      Motorcycling                 3140        Transgender        8353.0         Demisexual                    6301.0         Rural               8331.0            Low                7132.0          High School                 5632.0             Addicted                      9909.0      Swipe Maniac                   8276.0     Early Morning                   8320.0              Blocked               5049.0
3    Binge-Watching                 3131  Prefer Not to Say        8335.0              Queer                    6288.0      Suburban               8296.0         Middle                7126.0                  PhD                 5594.0             Moderate                      4999.0            Choosy                   3121.0        Late Night                   8287.0            Catfished               5025.0
4             Music                 3109        Genderfluid        8307.0            Asexual                    6254.0         Metro               8293.0   Lower-Middle                7118.0  No Formal Education                 5569.0                  Low                      2535.0               NaN                      NaN           Evening                   8269.0         Chat Ignored               5019.0
5              Yoga                 3108               Male        8255.0          Pansexual                    6237.0         Urban               8218.0   Upper-Middle                7076.0             Master’s                 5503.0             Very Low                      1623.0               NaN                      NaN           Morning                   8256.0         Mutual Match               4990.0
6         Investing                 3108                NaN           NaN           Bisexual                    6158.0           NaN                  NaN       Very Low                7061.0          Associate’s                 5499.0               Barely                       883.0               NaN                      NaN               NaN                      NaN            No Action               4986.0
7           Reading                 3106                NaN           NaN                Gay                    6121.0           NaN                  NaN            NaN                   NaN              Postdoc                 5473.0                  NaN                         NaN               NaN                      NaN               NaN                      NaN              Ghosted               4959.0
8       Photography                 3106                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN              Diploma                 5447.0                  NaN                         NaN               NaN                      NaN               NaN                      NaN        Date Happened               4919.0
9               Art                 3106                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN  Relationship Formed               4863.0
10        Traveling                 3100                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
11         Clubbing                 3097                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
12          Skating                 3096                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
13           Makeup                 3091                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
14          Dancing                 3087                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
15     Spirituality                 3085                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
16  Social Activism                 3085                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
17          Cooking                 3079                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
18      Board Games                 3076                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
19         Crafting                 3075                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
20             Cars                 3070                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
21           Hiking                 3070                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
22             Pets                 3070                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
23         Podcasts                 3069                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
24  Sneaker Culture                 3066                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
25         Politics                 3065                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
26         Startups                 3065                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
27        Languages                 3060                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
28          History                 3060                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
29           Movies                 3058                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
30        Parenting                 3056                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
31         Painting                 3053                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
32          Writing                 3050                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
33              MMA                 3049                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
34          Tattoos                 3048                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
35            Memes                 3046                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
36          Fashion                 3042                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
37           Foodie                 3033                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
38            K-pop                 3022                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
39        Gardening                 3008                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
40        Astrology                 3001                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
41            Anime                 2998                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
42             Tech                 2995                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
43           Poetry                 2990                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
44          Running                 2988                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
45  Stand-up Comedy                 2987                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN
46       Meditation                 2985                NaN           NaN                NaN                       NaN           NaN                  NaN            NaN                   NaN                  NaN                    NaN                  NaN                         NaN               NaN                      NaN               NaN                      NaN                  NaN                  NaN